name: Pipeline

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: pipeline-${{ github.ref }}
  cancel-in-progress: true

env:
  GOPRIVATE: github.com/akeylesslabs

jobs:
  lint:
